%YAML 1.2
---

distribution_name: 'Prevail'

internet_connection_required: yes

internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: no

suggested_languages:
    - 'en'
    - 'de'
    - 'es'
    - 'fr'
    - 'nl'
    - 'uk'

welcome_page:
    logo    : '/usr/share/pixmaps/prevail-logo.png'
    text    : 'This program will guide you through the process of installing Prevail to your PC'
    usage   : yes

minimum_disk_size: 20
offer_disk_encryption: yes

skip_user: no
skip_locale: no

failure_help_url: ''

browser_cmd: 'chromium'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'
